windowrule {
  name = floating-term
  match:class = Terminal

  float = on
  stay_focused = on
  no_initial_focus = on
  animation = popin
}

bindd = CTRL, return, Pop-Up Terminal, exec, ~/.config/hypr/terminal.sh
