windowrule {
  name = floating-term
  match:class = Terminal

  float = on
  stay_focused = on
  no_initial_focus = on
  center = on
  size = (monitor_w*0.98) (monitor_h*0.7)
  animation = popin
}

bindd = CTRL, return, Pop-Up Terminal, exec, ~/.config/hypr/terminal.sh
