# Assumes brew bundle has finished and installed all of the software

- hosts: localhost
  roles:
    # Shell
    - { role: shell, tags: shell }
    
    # Programming languages
    - { role: ruby, tags: ruby }
    - { role: node, tags: node }
