# Assumes brew bundle has finished and installed all of the software

- hosts: localhost
  roles:
    # Shell
    - { role: zshell, tags: zshell }
    
    # Programming languages
    - { role: ruby, tags: ruby }
    - { role: node, tags: node }
    
    # Dotfiles
    - { role: dotfiles, tags: dotfiles }

    # Misc
    - { role: gpg, tags: gpg }
