# Assumes brew bundle has finished and installed all of the software

- hosts: localhost
  roles:
    # Software
    - { role: base, tags: base }
    - { role: terminal, tags: terminal }
    - { role: clipboard, tags: clipboard }
    - { role: keyring, tags: keyring }
    - { role: web-apps, tags: web-apps }

    # Shell
    - { role: shell, tags: shell }
    
    # Programming languages
    - { role: ruby, tags: ruby }
    - { role: node, tags: node }
