---
- name: Create kitty configuration directory
  file:
    path: "{{ user.home }}/.config/kitty"
    state: directory

- name: Create kitty.conf
  copy:
    src: kitty.conf
    dest: "{{ user.home }}/.config/kitty/kitty.conf"
    backup: true

- name: Copy terminal script
  copy:
    src: terminal.sh
    dest: "{{ user.home }}/.config/hypr/terminal.sh"
    mode: '0755'
    backup: true

- name: Create hyprland terminal configuration
  copy:
    src: terminal.conf
    dest: "{{ user.home }}/.config/hypr/terminal.conf"
    backup: true

- name: Add terminal.conf source to hyprland.conf
  lineinfile:
    path: "{{ user.home }}/.config/hypr/hyprland.conf"
    line: "source = ~/.config/hypr/terminal.conf"
    create: no
    backup: true
