---
- name: Install clipboard management packages
  community.general.pacman:
    name:
      - cliphist
    state: latest
  become: true

- name: Create hyprland clipboard configuration
  copy:
    src: clipboard.conf
    dest: "{{ user.home }}/.config/hypr/clipboard.conf"

- name: Add clipboard.conf source to hyprland.conf
  lineinfile:
    path: "{{ user.home }}/.config/hypr/hyprland.conf"
    line: "source = ~/.config/hypr/clipboard.conf"
    create: no
    backup: true
