---
- name: Install extra packages
  community.general.pacman:
    name:
      - chezmoi
      - firefox
      - mkcert
      - ttf-firacode-nerd
      # terminal
      - kitty
      - zsh
      - diff-so-fancy
      - direnv
      - pass
      - btop
      - github-cli
      - glab
      - fzf
      - bat
      - eza
      - jq
      - lazygit
      - lazydocker
      - zoxide
      - starship
      - ncdu
      - git
      # cloud
      - k9s
      - helm
      - kubectl
      - kubectx
    state: latest
    update_cache: true
  become: true

- name: Install zed editor
  shell: curl -f https://zed.dev/install.sh | sh
