---
- name: Install extra packages
  community.general.pacman:
    name:
      - chezmoi
      - diff-so-fancy
      - direnv
      - firefox
      - kubectx
      - mkcert
      - ncdu
      - pass
      - visual-studio-code-bin
      - zsh
      - k9s
      - ttf-fira-code
      - yubikey-manager
    state: latest
    update_cache: true
  become: true

- name: Remove unneeded packages
  community.general.pacman:
    name:
      - 1password-beta
      - 1password-cli
      - signal-desktop
    state: absent
  become: true

- name: Create hyprland clipboard configuration
  copy:
    src: unbindings.conf
    dest: "{{ user.home }}/.config/hypr/unbindings.conf"

- name: Add unbindings.conf source to hyprland.conf
  lineinfile:
    path: "{{ user.home }}/.config/hypr/hyprland.conf"
    line: "# Additional custom configs\nsource = ~/.config/hypr/unbindings.conf"
    create: no
    backup: true

- name: Set firefox as default browser
  shell: xdg-settings set default-web-browser firefox.desktop
