---

# omarchy already uses LazyVim, keep this step in case it changes in the future
- name: Check whether Neovim config already exists
  stat:
    path: "{{ nvim_config }}"
  register: nvim_config_dir

- name: Clone lazyvim starter template
  git:
    repo: "{{ github }}LazyVim/starter.git"
    dest: "{{ nvim_config }}"
    accept_hostkey: yes
  when: not nvim_config_dir.stat.exists

- name: Add colorcolumn option
  lineinfile:
    path: "{{ nvim_config }}/init.lua"
    line: vim.opt.colorcolumn = "120"
    state: present

# It is recommended to run :LazyHealth after installation. This will load all plugins and check if everything is working correctly.
